set up associations
mrparkersson/school-library pull request #4
Opened 2022-04-07 09:42 UTC by mrparkersson

Pull request
Amo Parker Prince

What does this PR do?

This is a ruby work to Set up associations between classes and objects.

Description of the task to be completed

Implement the classes to represent students and teachers.

Used Ruby in creating all components

created test.MD files that have been ignored
How should it be tested
By running npm test in the terminal.

clone the repository
git clone https://github.com/mrparkersson/school-library
navigate to the folder
cd reactcapstone
checkout the feature

2022-04-07 10:20 UTC, mikethreels requested changes
Hi Parker, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] in the `Student` class there should be a method that serves as the 'belongs-to' side (a student belongs to a classroom). please have a look at [this article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#both-ways-relationships) with examples.
- [ ] in the `Person` class Getters and Setters for @rentals should be present.
- [ ] in the `Person` class @rentals should be initialized, have a look at [this article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/class_and_object_for_irb.md#constructor-and-instance-vars) for examples.
- [ ] in the `Person` class A method for adding rentals should be present. please have a look at [this article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship) for examples.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-07 16:12 UTC, Dipeshtwis requested changes
Hi @mrparkersson, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

**_Check the comments under the review_**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-07 16:12 UTC, Dipeshtwis commented on book.rb
> +  attr_accessor :title, :author
- [ ] Here make sure Getters and Setters for `@rentals` should be present. You have set only Getters.

Hint on how to set getter and setter.
`attr_accessor :rentals`

2022-04-07 16:12 UTC, Dipeshtwis commented on person.rb
> +  end
- [ ] In the Person class `@rentals` should be initialized, 

```ruby
def initialize(age, name = "Unknown", parent_permission = true)
    .
    .
    # *@rentals should be initialized. Link to the example about constructors in a previous lesson https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/class_and_object_for_irb.md#constructor-and-instance-vars
    @rentals = []
  end
```

2022-04-08 07:37 UTC, Kingstalux commented on person.rb
>    attr_accessor :name, :age
resolved 👍

2022-04-08 07:38 UTC, Kingstalux commented on person.rb
> +  end
resolved 👍

2022-04-08 07:38 UTC, Kingstalux commented on classroom.rb
> +  attr_reader :students
resolved 👍

2022-04-08 07:39 UTC, Kingstalux approved these changes
Hi @mrparkersson,
# Status: Approved ✔️ ✔️ ✔️ 
 
![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966](https://user-images.githubusercontent.com/85113567/162388482-6ff2d832-7ba6-4f0f-b418-12cce8cf2b30.gif)


Good job implementing the required changes 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-11 12:06 UTC, merged